export const MARKETS = [
  "am-et", "ar-ae", "ar-bh", "ar-dj", "ar-dz", "ar-eg", "ar-er", "ar-il",
  "ar-iq", "ar-jo", "ar-km", "ar-kw", "ar-lb", "ar-ly", "ar-ma", "ar-mr",
  "ar-om", "ar-ps", "ar-qa", "ar-sa", "ar-sd", "ar-so", "ar-sy", "ar-td",
  "ar-tn", "ar-ye", "az-az", "be-by", "bg-bg", "bn-bd", "bs-ba", "ca-ad",
  "cs-cz", "da-dk", "de-at", "de-be", "de-ch", "de-de", "de-li", "de-lu",
  "dv-mv", "dz-bt", "el-cy", "el-gr", "en-ag", "en-ai", "en-as", "en-au",
  "en-bb", "en-bi", "en-bm", "en-bs", "en-bw", "en-bz", "en-ca", "en-cc",
  "en-ck", "en-cm", "en-cx", "en-dm", "en-er", "en-fj", "en-fk", "en-fm",
  "en-gb", "en-gd", "en-gg", "en-gh", "en-gi", "en-gm", "en-gu", "en-gy",
  "en-hk", "en-ie", "en-in", "en-je", "en-jm", "en-ke", "en-ki", "en-kn",
  "en-ky", "en-lc", "en-lr", "en-ls", "en-mg", "en-mh", "en-mp", "en-ms",
  "en-mt", "en-mu", "en-mw", "en-na", "en-nf", "en-ng", "en-nr", "en-nu",
  "en-nz", "en-pg", "en-ph", "en-pk", "en-pn", "en-pr", "en-pw", "en-rw",
  "en-sb", "en-sc", "en-sd", "en-sg", "en-sh", "en-sl", "en-ss", "en-sx",
  "en-sz", "en-tc", "en-tk", "en-to", "en-tt", "en-tv", "en-tz", "en-ug",
  "en-us", "en-vc", "en-vg", "en-vi", "en-vu", "en-ws", "en-za", "en-zm",
  "en-zw", "es-ar", "es-bo", "es-cl", "es-co", "es-cr", "es-do", "es-ec",
  "es-es", "es-gq", "es-gt", "es-hn", "es-mx", "es-ni", "es-pa", "es-pe",
  "es-pr", "es-py", "es-sv", "es-uy", "es-ve", "et-ee", "fa-af", "fa-ir",
  "fi-fi", "fil-ph", "fo-fo", "fr-be", "fr-bf", "fr-bi", "fr-bj", "fr-bl",
  "fr-ca", "fr-cd", "fr-cf", "fr-cg", "fr-ch", "fr-ci", "fr-cm", "fr-dj",
  "fr-dz", "fr-fr", "fr-ga", "fr-gf", "fr-gn", "fr-gp", "fr-gq", "fr-ht",
  "fr-km", "fr-lu", "fr-ma", "fr-mc", "fr-mf", "fr-mg", "fr-ml", "fr-mq",
  "fr-mu", "fr-nc", "fr-ne", "fr-pf", "fr-pm", "fr-re", "fr-rw", "fr-sc",
  "fr-sn", "fr-td", "fr-tg", "fr-tn", "fr-vu", "fr-wf", "fr-yt", "ga-ie",
  "gn-py", "gsw-ch", "gsw-li", "he-il", "hi-in", "hr-ba", "hr-hr", "ht-ht",
  "hu-hu", "hy-am", "id-id", "is-is", "it-ch", "it-it", "it-sm", "it-va",
  "ja-jp", "ka-ge", "kk-kz", "kl-gl", "km-kh", "ko-kr", "ky-kg", "lb-lu",
  "lo-la", "lt-lt", "lv-lv", "mg-mg", "mi-nz", "mk-mk", "mn-mn", "ms-bn",
  "ms-my", "ms-sg", "mt-mt", "my-mm", "nb-no", "nd-zw", "ne-np", "nl-aw",
  "nl-be", "nl-cw", "nl-nl", "nl-sr", "nl-sx", "nn-no", "ny-mw", "pap-aw",
  "pap-cw", "pl-pl", "ps-af", "pt-ao", "pt-br", "pt-cv", "pt-gq", "pt-gw",
  "pt-mo", "pt-mz", "pt-pt", "pt-st", "qu-bo", "qu-ec", "qu-pe", "rn-bi",
  "ro-md", "ro-ro", "ru-by", "ru-kg", "ru-kz", "ru-ru", "ru-ua", "rw-rw",
  "sg-cf", "si-lk", "sk-sk", "sl-si", "sn-zw", "so-so", "sq-al", "sr-ba",
  "sr-me", "sr-rs", "ss-sz", "st-ls", "sv-fi", "sv-se", "sw-ke", "sw-tz",
  "sw-ug", "ta-lk", "ta-sg", "tg-tj", "th-th", "ti-er", "tk-tm", "tn-bw",
  "to-to", "tpi-pg", "tr-cy", "tr-tr", "tzm-ma", "uk-ua", "ur-pk", "uz-uz",
  "vi-vn", "wo-sn", "yo-ng", "yue-mo", "zh-cn", "zh-mo", "zh-sg", "zh-tw",
];

export const regions = [
  ...new Set(MARKETS.map((market) => market.slice(market.lastIndexOf("-") + 1).toUpperCase())),
];
