export const REGION_COUNTRIES = {
  "ar-SA": "sa",
  "da-DK": "dk",
  "de-AT": "at",
  "de-BE": "be",
  "de-CH": "ch",
  "de-DE": "de",
  "en-AU": "au",
  "en-CA": "ca",
  "en-GB": "gb",
  "en-HK": "hk",
  "en-IN": "in",
  "en-NZ": "nz",
  "en-PH": "ph",
  "en-US": "us",
  "en-ZA": "za",
  "es-AR": "ar",
  "es-CL": "cl",
  "es-ES": "es",
  "es-MX": "mx",
  "fi-FI": "fi",
  "fil-PH": "ph",
  "fr-BE": "be",
  "fr-CA": "ca",
  "fr-CH": "ch",
  "fr-FR": "fr",
  "gsw-CH": "ch",
  "hi-IN": "in",
  "id-ID": "id",
  "it-CH": "ch",
  "it-IT": "it",
  "ja-JP": "jp",
  "ko-KR": "kr",
  "mi-NZ": "nz",
  "ms-MY": "my",
  "nb-NO": "no",
  "nl-BE": "be",
  "nl-NL": "nl",
  "nn-NO": "no",
  "pl-PL": "pl",
  "pt-BR": "br",
  "pt-PT": "pt",
  "ru-RU": "ru",
  "sv-FI": "fi",
  "sv-SE": "se",
  "tr-TR": "tr",
  "zh-CN": "cn",
  "zh-HK": "hk",
  "zh-TW": "tw",
};

export const regions = [
  ...new Set(Object.keys(REGION_COUNTRIES).map((locale) => locale.slice(locale.lastIndexOf("-") + 1))),
];
