export const REGION_PREFERENCES = {
  "ar-EG": "ar_EG",
  "bg-BG": "bg_BG",
  "ca-ES": "ca_ES",
  "cs-CZ": "cs_CZ",
  "da-DK": "da_DK",
  "de-AT": "de_AT",
  "de-CH": "de_CH",
  "de-DE": "de_DE",
  "el-GR": "el_GR",
  "en-AU": "en_AU",
  "en-CA": "en_CA",
  "en-GB": "en-GB_GB",
  "en-ID": "en_ID",
  "en-IE": "en_IE",
  "en-IN": "en_IN",
  "en-MY": "en_MY",
  "en-NZ": "en_NZ",
  "en-PH": "en_PH",
  "en-SG": "en_SG",
  "en-US": "en_US",
  "en-ZA": "en_ZA",
  "es-AR": "es_AR",
  "es-CL": "es_CL",
  "es-CO": "es_CO",
  "es-ES": "es_ES",
  "es-MX": "es_MX",
  "es-PE": "es_PE",
  "es-US": "es_US",
  "es-UY": "es_UY",
  "es-VE": "es_VE",
  "et-EE": "et_EE",
  "fi-FI": "fi_FI",
  "fil-PH": "fil_PH",
  "fr-BE": "fr_BE",
  "fr-CA": "fr_CA",
  "fr-CH": "fr_CH",
  "fr-FR": "fr_FR",
  "hi-IN": "hi_IN",
  "hu-HU": "hu_HU",
  "id-ID": "id_ID",
  "it-CH": "it_CH",
  "it-IT": "it_IT",
  "ja-JP": "ja_JP",
  "ko-KR": "ko_KR",
  "ms-MY": "ms_MY",
  "ms-SG": "ms_SG",
  "nb-NO": "no_NO",
  "nl-BE": "nl_BE",
  "nl-NL": "nl_NL",
  "pl-PL": "pl_PL",
  "pt-BR": "pt-BR_BR",
  "pt-PT": "pt_PT",
  "ro-RO": "ro_RO",
  "ru-BY": "ru_BY",
  "ru-RU": "ru_RU",
  "sv-SE": "sv_SE",
  "tr-TR": "tr_TR",
  "uk-UA": "uk_UA",
  "vi-VN": "vi_VN",
  "zh-CN": "zh-CN_CN",
  "zh-HK": "zh-TW_HK",
  "zh-TW": "zh-TW_TW",
};

export const regions = [
  ...new Set(Object.keys(REGION_PREFERENCES).map((locale) => locale.slice(locale.lastIndexOf("-") + 1))),
];
