export const filters = {
  size: ["small", "medium", "large", "wallpaper"],
  color: [
    "monochrome",
    "red",
    "orange",
    "yellow",
    "green",
    "teal",
    "blue",
    "purple",
    "pink",
    "white",
    "gray",
    "brown",
    "black",
    "transparent",
  ],
  type: ["photo", "clipart", "lineart", "animated"],
  layout: ["square", "wide", "tall"],
  nsfw: ["on", "moderate", "off"],
};
