export const regions = [
  "AD", "AE", "AF", "AG", "AM", "AO", "AR", "AS", "AT", "AU",
  "BA", "BE", "BF", "BG", "BH", "BI", "BJ", "BO", "BR", "BS",
  "BW", "BY", "BZ", "CA", "CD", "CF", "CG", "CH", "CI", "CK",
  "CL", "CM", "CO", "CR", "CU", "CV", "CY", "CZ", "DE", "DJ",
  "DK", "DM", "DO", "DZ", "EC", "EE", "EG", "ES", "FI", "FJ",
  "FM", "FR", "GA", "GB", "GG", "GH", "GI", "GM", "GR", "GT",
  "GY", "HK", "HN", "HR", "HT", "HU", "ID", "IE", "IL", "IM",
  "IN", "IQ", "IS", "IT", "JE", "JM", "JO", "JP", "KE", "KG",
  "KI", "KR", "KW", "KZ", "LB", "LI", "LS", "LT", "LU", "LV",
  "LY", "MA", "MD", "MG", "ML", "MT", "MU", "MW", "MX", "MZ",
  "NA", "NE", "NG", "NI", "NL", "NO", "NR", "NU", "NZ", "OM",
  "PA", "PE", "PG", "PH", "PK", "PL", "PN", "PR", "PS", "PT",
  "PY", "QA", "RO", "RS", "RU", "RW", "SA", "SB", "SC", "SE",
  "SG", "SH", "SI", "SK", "SL", "SM", "SN", "SO", "SR", "ST",
  "SV", "TD", "TG", "TH", "TL", "TN", "TO", "TR", "TT", "TW",
  "TZ", "UA", "UG", "US", "UY", "VC", "VE", "VI", "VN", "VU",
  "WS", "ZA", "ZM", "ZW",
];
