export const REGION_LOCALES = {
  "ar-SA": "xa-ar",
  "bg-BG": "bg-bg",
  "ca-ES": "es-ca",
  "cs-CZ": "cz-cs",
  "da-DK": "dk-da",
  "de-AT": "at-de",
  "de-CH": "ch-de",
  "de-DE": "de-de",
  "el-GR": "gr-el",
  "en-AU": "au-en",
  "en-CA": "ca-en",
  "en-GB": "uk-en",
  "en-IE": "ie-en",
  "en-IL": "il-en",
  "en-IN": "in-en",
  "en-MY": "my-en",
  "en-NZ": "nz-en",
  "en-PH": "ph-en",
  "en-PK": "pk-en",
  "en-SG": "sg-en",
  "en-US": "us-en",
  "en-ZA": "za-en",
  "es-AR": "ar-es",
  "es-CL": "cl-es",
  "es-CO": "co-es",
  "es-ES": "es-es",
  "es-MX": "mx-es",
  "es-PE": "pe-es",
  "es-US": "us-es",
  "et-EE": "ee-et",
  "fi-FI": "fi-fi",
  "fr-BE": "be-fr",
  "fr-CA": "ca-fr",
  "fr-CH": "ch-fr",
  "fr-FR": "fr-fr",
  "hr-HR": "hr-hr",
  "hu-HU": "hu-hu",
  "id-ID": "id-en",
  "is-IS": "is-is",
  "it-IT": "it-it",
  "ja-JP": "jp-jp",
  "ko-KR": "kr-kr",
  "lt-LT": "lt-lt",
  "lv-LV": "lv-lv",
  "nb-NO": "no-no",
  "nl-BE": "be-nl",
  "nl-NL": "nl-nl",
  "pl-PL": "pl-pl",
  "pt-BR": "br-pt",
  "pt-PT": "pt-pt",
  "ro-RO": "ro-ro",
  "ru-RU": "ru-ru",
  "sk-SK": "sk-sk",
  "sl-SI": "sl-sl",
  "sv-SE": "se-sv",
  "th-TH": "th-en",
  "tr-TR": "tr-tr",
  "uk-UA": "ua-uk",
  "vi-VN": "vn-en",
  "zh-CN": "cn-zh",
  "zh-HK": "hk-tzh",
  "zh-TW": "tw-tzh",
};

export const regions = [
  ...new Set(Object.keys(REGION_LOCALES).map((locale) => locale.slice(locale.lastIndexOf("-") + 1))),
];
